print("Kiểu số là các số thuộc số nguyên, thực, phức")
print("các số không nằm trong dấu ngoặc kép")
print("kiểu chuỗi là các kí tự nối liền nhau")
print("chuỗi nằm giữa hai dấu ngoặc kép")
print("chuyển các kí tự số trong chuỗi thành loại số dùng int sang số nguyên")
print("chuyển các kí tự số trong chuỗi thành giá số có dấu phẩy động : float")
print("vd:")
n = int(input("nhập số"))
print("số đó nhân 2 là",2*n)
x = float(input("nhập số"))
print("số đó trong dạng float là",x)
print("để chuyển 1 số sang 1 kí tự trong chuỗi thì dùng str")
print("vd:")
g = str(input("nhập số"))
print("vậy số đó là "+g)